
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.8.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  hotels:
    build: ./services/hotels
    depends_on:
      - mongo
      - kafka
    environment:
      - MONGO_URL=mongodb://mongo:27017/hotelDB
      - KAFKA_BROKER=kafka:9092

  reservations:
    build: ./services/reservations
    depends_on:
      - mongo
      - kafka
    environment:
      - MONGO_URL=mongodb://mongo:27017/reservationsDB
      - KAFKA_BROKER=kafka:9092

  notifications:
    build: ./services/notifications
    depends_on:
      - kafka

  payments:
    build: ./services/payments
    depends_on:
      - kafka

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - hotels
      - reservations
      - payments

volumes:
  mongo_data: 